import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'Peter WJ',
      email: 'adminbag@example.com',
      password: bcrypt.hashSync(process.env.ADMIN_PASSWORD),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Slim Shirt',
      slug: 'slim-shirt',
      category: 'Shirts',
      images: [
        '/images/shirt1.jpg',
        '/images/shirt2.jpg',
        '/images/shirt3.jpg',
        '/images/pants1.jpg',
        '/images/pants2.jpg',
      ],
      price: 90,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Golf Pants',
      slug: 'golf-pants',
      category: 'Pants',
      images: [
        '/images/shirt1.jpg',
        '/images/shirt2.jpg',
        '/images/shirt3.jpg',
        '/images/pants1.jpg',
        '/images/pants2.jpg',
      ],
      price: 90,
      brand: 'Oliver',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Smart looking pants',
    },
    {
      name: 'Fit Pants',
      slug: 'fit-pants',
      category: 'Pants',
      images: [
        '/images/shirt1.jpg',
        '/images/shirt2.jpg',
        '/images/shirt3.jpg',
        '/images/pants1.jpg',
        '/images/pants2.jpg',
      ],
      price: 95,
      brand: 'Zara',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular pants',
    },
    {
      name: 'Classic Pants',
      slug: 'a-pants',
      category: 'Pants',
      images: [
        '/images/shirt1.jpg',
        '/images/shirt2.jpg',
        '/images/shirt3.jpg',
        '/images/pants1.jpg',
        '/images/pants2.jpg',
      ],
      price: 75,
      brand: 'Casely',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular pants',
    },
    {
      name: 'Classic Pants',
      slug: 'b-pants',
      category: 'Pants',
      images: [
        '/images/shirt1.jpg',
        '/images/shirt2.jpg',
        '/images/shirt3.jpg',
        '/images/pants1.jpg',
        '/images/pants2.jpg',
      ],
      price: 75,
      brand: 'Casely',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular pants',
    },
    {
      name: 'Classic Pants',
      slug: 'c-pants',
      category: 'Pants',
      images: [
        '/images/shirt1.jpg',
        '/images/shirt2.jpg',
        '/images/shirt3.jpg',
        '/images/pants1.jpg',
        '/images/pants2.jpg',
      ],
      price: 75,
      brand: 'Casely',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular pants',
    },
    {
      name: 'Classic Pants',
      slug: 'd-pants',
      category: 'Pants',
      images: [
        '/images/shirt1.jpg',
        '/images/shirt2.jpg',
        '/images/shirt3.jpg',
        '/images/pants1.jpg',
        '/images/pants2.jpg',
      ],
      price: 75,
      brand: 'Casely',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular pants',
    },
  ],
};
export default data;
